<?php

namespace AppBundle\Repository;

/**
 * GroupActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
