<?php

namespace AppBundle\Repository;

/**
 * NotificationSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
